rtfmコマンドを追加
free-RT/rt-bot pull request #65
Opened 2022-04-24 06:32 UTC by gx1285

2022-04-24 10:24 UTC, yaakiyu requested changes
変更を要求

2022-04-24 10:24 UTC, yaakiyu commented on cogs/rtfm.py
> +    async def on_ready(self):
おそらくどっかのサンプルをコピペしたんだろうけど
on_readyはまず呼ばれないのでいらない

2022-04-24 10:24 UTC, yaakiyu commented on cogs/rtfm.py
> +            async with aiohttp.ClientSession() as session:
self.bot.sessionを使って欲しい。

2022-04-24 10:30 UTC, gx1285 reviewed
　OK

2022-04-24 11:56 UTC, yaakiyu requested changes
1箇所変更を要求

2022-04-24 11:56 UTC, yaakiyu commented on cogs/rtfm.py
> +            async with self.bot.ClientSession() as session:
`self.bot.ClientSession()`ではなく
self.bot.sessionというものがあるのでそれを使って欲しい。
具体的にはこの行を消して次の行を`async with self.bot.session...`みたいにしてほしい

2022-04-25 09:18 UTC, yaakiyu approved these changes

2022-04-25 09:19 UTC, merged