change: bot_general内になるURLや、テキストを正しいものに更新。
free-RT/rt-bot pull request #69
Opened 2022-04-26 12:49 UTC by kousakirai

2022-04-26 12:49 UTC, kousakirai commented
一応チェックよろ

2022-04-26 13:29 UTC, yaakiyu requested changes
変更要求よろぴく()

2022-04-26 13:29 UTC, yaakiyu commented on cogs/bot_general.py
> +INFO_GITHUB = """* [RT-Team](https://github.com/free-RT)
名前がrt-teamのままになっている。

2022-04-29 13:39 UTC, yaakiyu approved these changes
自分の変更に自分でapproveする人()

2022-04-29 13:39 UTC, merged